server:
  socket-port: 2207
  late-joiners-buffer-size: 1000
  stay-active: false
  
  startup:
    - command: "echo \"startup 1\""
    - command: "sleep 5"
    - command: "echo \"startup 2\""

  shutdown:
    - command: "echo \"shutdown\""

  endpoints:
    - type: "subprocess"
      name: "command"
      short-name: "sh"
      command: "./test1.sh"

      commands:
        test1:
          command: "./test1.sh"
          auto-run: false
        test2:
          command: "./test2.sh"
          auto-run: false

views:
  main:
    show-endpoints: all
    formats:
      - endpoint: "command"
        default:
          background-color: none
          foreground-color: white
        stderr:
          background-color: red1
          foreground-color: red8
      - endpoint: "_"
        marker:
          background-color: green1
          foreground-color: green7
      - register: 'x'
        regex: ".py"
        background-color: blue1
        foreground-color: blue8
        enabled: true


    line-format: "{format:filter}{watch-symbol}[{endpoint:8}] {seq:_6} {time}\u2503 {format:default}{data}"
    marker-format: "{format:endpoint}[ MARKER ] >>>>>> {time}\u2503 {name} <<<<<<"
    filtered: false
    max-held-lines: 5000

  filtered:
    line-format: "{format:filter}{watch-symbol} {fd} {seq:6} {time}{format:reset} {data}"
    filtered: true
    formats:
      - register: 'p'
        regex: '.py'
        background-color: blue7
        foreground-color: black
        enabled: true

layouts:
  tmux:
    engine: tmux
    run-server: true
    layout: classic-horizontal
    panels:
      - view: main
      - view: filtered
        filters-panel: true
        size: 12

