server:
  socket-port: 2207
  endpoints:
    - type: "subprocess"
      name: "command"
      short-name: "sh"
      command: "./test1.sh"

      commands:
        test1:
          command: "./test1.sh"
          auto-run: false
        test2:
          command: "./test2.sh"
          auto-run: false

views:
  main:
    show-endpoints: all
    formats:
      - endpoint: "command"
        stdout:
          background-color: none
          foreground-color: white
        stderr:
          background-color: red1
          foreground-color: red8
      - endpoint: "_"
        marker:
          background-color: green1
          foreground-color: green7

    line-format: "{format:endpoint}[{endpoint:8}] {seq:_6} {time}\u2503 {data}"
    marker-format: "{format:endpoint}[ MARKER ] >>>>>> {time}\u2503 {name} <<<<<<"
    filtered: false

  filtered:
    socket-port: 2208
    line-format: "{format:filter}[{filter}] {fd} {seq:6} {time}{format:reset} {data}"
    filtered: true
    formats:
      - regex: '.py'
        background-color: blue7
        foreground-color: black
        enabled: true
